version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - flask

  flask:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
